### ISSUE TITLE
Can't edit anything with this

### ISSUE THREAD

**Issue by SamusAranX** [kwsch/NLSE#2]
All the controls in the window are disabled.
When dropping a valid AC:NL file on it, I get this:

```
File checksums were not updated (already valid):
\\psf\Home\Desktop\acnl\garden.dat
```

I know the files are valid because the web-based editor can edit and save them.
Am I doing anything wrong or is this just a bug?

**Comment by kwsch** [comment]
Drop the folder that contains the save file, not the individual file(s) (ie, garden.dat).

Individual file drag&drop is used for individual file fixing (checksums) as you have noted; this is so that users can tamper with their saves in a Hex Editor and automatically fix the changes.

If you are having trouble with getting the folder to be recognized, try clicking on the label above all of the buttons to open the FolderBrowserDialog to select the folder. Another user on GBATemp has noticed there is an issue and I will investigate later.

**Comment by SamusAranX** [comment]
Nothing happens if I do that. Literally nothing, not even a message box.
Are you doing path validation behind the scenes? I'm running this in a Windows 8.1 VM on OS X 10.11, so the folder paths are a little weird, as you can see above. Might this be a possible cause?

Edit: Never mind, clicking the label and manually selecting the folder worked. Please make this more obvious. :smile:

**Comment by kwsch** [comment]
Possibly. I've updated my first comment with the existing workaround. Try that :+1:

The problem may be with the [loading of the drag&drop paths](https://github.com/kwsch/NLSE/blob/master/Main.cs#L43) (my note for later)

**Comment by SamusAranX** [comment]
Um... There's just one thing left: Am I right in assuming that I can't edit my bank account with this editor?

**Comment by kwsch** [comment]
I don't own AC:NL so I cannot do my own research as to what offset stores player balance.

You can always insert bags of money around the map, or in your inventory!

**Comment by SamusAranX** [comment]
I'm already doing this, but I'm a lazy bastard and wondered if there's a better way.
Also, [the source code of LeafTools (the thingy with the pre-9.5 QR codes)](https://bitbucket.org/neokamek/leaftools/src/712bbbb9d97d2d601510458634ce603bd7b9b9af/lt-bank.c?at=default) might help you with figuring out the offsets.
I'd submit a pull request, but it's been years since I've last touched C#.

**Comment by kwsch** [comment]
https://gbatemp.net/threads/spider-animal-crossing-new-leaf-save-editor.382965/page-22#post-5390010

The values aren't stored in any standard type of format; I'd rather display the actual value instead of having a cheat-button (since I can't directly confirm the offset I'm changing is correct).

From what I can tell, all offsets from LeafTools need to be shifted by +0x80 to line up with garden.dat offsets. So, that code would be:
0x6C0C=0x8CF95678
0x6C10=0x0D118636

Again I'm not sure if they line up exactly like that :\

**Comment by SamusAranX** [comment]
I just dumped two AC:NL saves, one with 16.000.000 bells in my account and one with 17.000.000 bells in my account, and put them next to each other in a hex editor.

![Hex Fiend displaying a file comparison](https://cloud.githubusercontent.com/assets/676069/9643708/edfd7f02-51c3-11e5-8902-9db9b9a4e427.png)

0x6C0C and 0x6C10 both seem to point to important values, but there's another value at 0x6C08 that also changed when putting another million into my bell account. I wish I knew how NeoKamek got those hex values for LeafTools. :|

**Comment by kwsch** [comment]
He probably manually deposited that amount of bells and checked what the hex value was. Then he just hard-coded it as a 'max bank' code.

78 56 F9 8C 36 86 11 0D

Try writing in ^ @ 0x6C0C

**Comment by kwsch** [comment]
Implemented "Max Bank balance" cheat from leaftools in latest commit.

https://github.com/kwsch/NLSE/commit/9ed10d84ecbbe9e1271ba36a0217617f719a614d

Compiled binary: https://github.com/kwsch/NLSE/releases/tag/v0.4
