### ISSUE TITLE
Two Issues

### ISSUE THREAD

**Issue by kyupos** [kwsch/NLSE#8]
Hey! Thanks so much for your work, I thought I'd tell you about a few bugs I found: Some of the hair color options are off, and the option to change the town name does not change every entry of it in the game (the villagers will refer to it as the new name but it will be the old name in other places). Thank you again.

**Comment by kwsch** [comment]
I've pushed a commit to change all instances of the Town Data https://github.com/kwsch/NLSE/commit/9a7ea098eeb1f7acf7979b56e4708a1506b44d0e, however I'm unsure what you mean by Hair Color being off.

Referring to the [ACNL spreadsheet posted hair color image](http://i.imgur.com/J2lhcDY.png) NLSE should match one to one (although, looks like I misidentified 08 as "Dark Green" instead of "Black" -- fixed https://github.com/kwsch/NLSE/commit/507bc8db0a94bd1960ea4cc70a98a60e2a6c9b47#diff-1449f0c64a5a3bbdd3d9d78d570aa8c0L1527).

Can you provide clarification on this?

**Comment by kyupos** [comment]
(Sorry for not being clear) I believe for some of the hair colors they're not labeled correctly, I know for instance Gray is actually Light Green and vice versa.
